# Generated by Django 5.2.2 on 2025-06-20 07:41

import alumni.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('is_employed', models.BooleanField(default=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to=alumni.models.resume_upload_path)),
                ('position', models.CharField(blank=True, help_text='Current position/title at employer (if employed)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-graduation_year', 'user__last_name'],
            },
        ),
    ]
