# Generated by Django 5.2.2 on 2025-06-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumni', '0001_initial'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employers.employer'),
        ),
    ]
